version: '3'
services:
    web:
        build: ./front-end
        ports:
            - '4200:4200'
        depends_on:
            - api
    api:
        build: ./back-end
        ports:
            - '5000:80'
        depends_on:
            - db
    db:
        image: postgres
        environment:
          POSTGRES_USER: 'razapp'
          POSTGRES_PASSWORD: 'razapp'
          POSTGRES_DB: 'razapp'
        ports:
          - '5432:5432'
