version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        de:
            - db
    db:
        image: postgres
        environment:
          POSTGRES_USER: 'razapp'
          POSTGRES_PASSWORD: 'razapp'
          POSTGRES_DB: 'razapp'
        ports:
          - '5432:5432'
